catalog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('triangle/', include('triangle.urls')),
]

django_catalog/urls.py
from django.contrib import admin
from django.urls import include, path

from triangle.views import first_page

urlpatterns = [
    path('', first_page, name='first-page'),
    path('admin/', admin.site.urls),
    path('triangle/', include('triangle.urls')),
]

triangle/urls.py
from django.urls import path

from triangle.views import PersonIndexView, first_page, get_form, person_create_form, person_update_form

app_name = 'triangle'
urlpatterns = [
    path('', get_form, name='triangle'),
    path('first-page/', first_page, name='first_page'),
    path('person-list/', PersonIndexView.as_view(), name='person_list'),
    path('person/', person_create_form, name='person_create_form'),
    path('person/<int:pk>/', person_update_form, name='person_update_form'),
]

catalog_app/models.py
from django.db import models


class Town(models.Model):
    town_name = models.CharField(max_length=255)

    def __str__(self):
        return self.town_name


class Client(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    product = models.ManyToManyField("Product", verbose_name="product", blank=True)
    town = models.ForeignKey("Town", verbose_name="town", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.last_name


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.product_name


class Retailer(models.Model):
    first_name = models.CharField(max_length=255)
    town = models.OneToOneField("Town", verbose_name="town", on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

triangle/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

    def __str__(self):
        return self.first_name


class Log(models.Model):
    path = models.CharField(max_length=30)
    method = models.CharField(max_length=30)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.path

triangle/forms.py
from django import forms

from triangle.models import Person


class GetForm(forms.Form):
    leg1 = forms.IntegerField(label='Leg 1', required=True, min_value=1)
    leg2 = forms.IntegerField(label='Leg 2', required=True, min_value=1)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

triangle/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic

from triangle.forms import GetForm, PersonForm
from triangle.models import Person


def first_page(request):
    return render(request, "triangle/first_page.html")


def get_form(request):
    hypotenuse = None
    if 'submit' in request.GET:
        get_form = GetForm(request.GET)
        if get_form.is_valid():
            leg1 = get_form.cleaned_data['leg1']
            leg2 = get_form.cleaned_data['leg2']
            hypotenuse = round(((leg1 ** 2 + leg2 ** 2) ** 0.5), 2)
    else:
        get_form = GetForm()
    return render(
        request,
        'triangle/triangle.html',
        {'get_form': get_form,
         'hypotenuse': hypotenuse, }
    )


def person_create_form(request):
    if request.method == 'POST':
        person_form = PersonForm(data=request.POST)
        if person_form.is_valid():
            person_form.save()
            return redirect('triangle:person_list')
    else:
        person_form = PersonForm()
    return render(
        request,
        "triangle/person_create_form.html",
        {
            'person_form': person_form
        }
    )


def person_update_form(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        person_form = PersonForm(data=request.POST, instance=person)
        if person_form.is_valid():
            person_form.save()
            return redirect('triangle:person_list')
    else:
        person_form = PersonForm(instance=person)
    return render(
        request,
        "triangle/person_update_form.html",
        {
            'person_form': person_form,
            'person': person,
        }
    )


class PersonIndexView(generic.ListView):
    template_name = 'triangle/person_list.html'
    context_object_name = 'person_list'

    def get_queryset(self):
        return Person.objects.all()

triangle/templates/triangle/first_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Description</title>
    <h1>Links page:</h1>
</head>
<body>
    <p><a href="{% url 'triangle:triangle' %}">Find hypotenuse</a></p>
    <p><a href="{% url 'triangle:person_create_form' %}">Person Create Form</a></p>
    <p><a href="{% url 'triangle:person_list' %}">Person List Form</a></p>
</body>
</html>

triangle/templates/triangle/person_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person Form</title>
</head>
<body>
    <form action="{% url 'triangle:person_create_form' %}" method="post">
        {% csrf_token %}
        {{ person_form.as_p }}
        <input type="submit" name="submit" value="OK">
    </form>
    <p><a href="{% url 'first-page' %}">Back to links page</a></p>
</body>
</html>

triangle/templates/triangle/person_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person list</title>
</head>
<body>
    <h1><a href="{% url 'triangle:person_create_form' %}">Person Create Form</a></h1>

    {% for person in person_list %}
        <p><a href="{% url 'triangle:person_update_form' pk=person.pk %}">
            {{ person.first_name }} {{ person.last_name }} {{ person.email }}</a></p>
    {% endfor %}
    <p><a href="{% url 'first-page' %}">Back to links page</a></p>

</body>
</html>

triangle/templates/triangle/person_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person Update Form</title>
</head>
<body>
    <form action="{% url 'triangle:person_update_form' pk=person.pk %}" method="post">
        {% csrf_token %}
        {{ person_form.as_p }}
        <input type="submit" name="submit" value="OK">
    </form>
    <p><a href="{% url 'first-page' %}">Back to links page</a></p>
</body>
</html>

triangle/templates/triangle/triangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle</title>
</head>
<body>
    <h1>Hypotenuse Calculator</h1>
    <form action="{% url 'triangle:triangle' %}" method="get">
        {{ get_form.as_p }}
        <input type='submit' name='submit' value='='>
    </form>
    {% if hypotenuse %}
        <p>The hypotenuse is {{ hypotenuse }}</p>
    {% endif %}
    <p><a href="{% url 'triangle:triangle' %}">Clear</a></p>
    <p><a href="{% url 'first-page' %}">Back to links page</a></p>
</body>
</html>